apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-svc-1804
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-svc-1804
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
